kind: Service
apiVersion: v1
metadata:
  name: shop-it-frontend-service
spec:
  type: ClusterIP
  selector:
    app: shop-it-frontend
  ports:
    - name: rest
      protocol: TCP
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-it-frontend-deployment
  labels:
    app: shop-it-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-it-frontend
  template:
    metadata:
      labels:
        app: shop-it-frontend
    spec:
      containers:
        - name: shop-it-frontend
          image: shop-it-frontend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: REACT_APP_SHOP_IT_BACKEND
              value: http://localhost/_api/shop-it/v1
