swagger: "2.0"
info:
  description: Shop-It
  version: 1.0.0
  title: Shop-It
  contact:
    email: dornakash94@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
tags:
  - name: products
  - name: shop
schemes:
  - http
  - https
paths:
  /products:
    post:
      tags:
        - product
      summary: create a new product
      operationId: createProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/CreateProductRequest"
      responses:
        "200":
          description: Product created succesfully
          schema:
            $ref: "#/definitions/CreateProductResponse"
        "400":
          description: bad input
  /products/{productId}:
    put:
      tags:
        - product
      summary: edit existing product
      operationId: editProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/ProductIdPath"
        - $ref: "#/parameters/EditProductRequest"
      responses:
        "200":
          description: Product edited successfully
          schema:
            $ref: "#/definitions/EditProductResponse"
        "400":
          description: bad input 
        "404":
          description: product doesn't exists
    delete:
      tags:
        - product
      summary: delete existing product
      operationId: deleteProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/ProductIdPath"
      responses:
        "204":
          description: Product deleted successfully
        "404":
          description: product doesn't exist
  /products/list:
    get:
      tags:
        - product
      summary: list existing products
      operationId: listProducts
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/PageNumberQuery"
        - $ref: "#/parameters/PageSizeQuery"
        - $ref: "#/parameters/FieldMaskQuery"
          #valid values: ["id","title","description","price","image","creationTime"]
      responses:
        "200":
          description: list of product
          schema:
            $ref: "#/definitions/ListProductsResponse"
            
  /shop/purchase:
    post:
      tags:
        - shop
      operationId: purchase
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - $ref: "#/parameters/PurchaseRequest"
      responses:
        "200":
          description: purchased succesfully
          schema:
            $ref: "#/definitions/PurchaseResponse" 
        "400":
          description: bad input
          
          
  /shop/stats:
    get:
      tags:
        - shop
      operationId: get stats of sales
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        "200":
          description: Stats returend succesfully
          schema:
            $ref: "#/definitions/GetStatsResponse"
          
 
parameters:
  PageSizeQuery:
    in: query
    name: page-size
    description: Page size
    type: integer
    minimum: 1
    maximum: 50
    default: 30
    required: false
  PageNumberQuery:
    in: query
    name: page-number
    description: current page
    type: integer
    minimum: 0
    default: 0
    required: false
  FieldMaskQuery:
    in: query
    name: field-mask
    type: array
    items:
      type: string
  
  ProductIdPath:
    in: path
    name: productId
    type: integer
    format: int64
    required: true
  
  CreateProductRequest:
    in: body
    name: "CreateProductRequest"
    required: true
    schema:
      required:
        - product
      type: object
      properties:
        product:
          $ref: "#/definitions/Product"
  EditProductRequest:
    in: body
    name: "EditProductRequest"
    required: true
    schema:
      type: object
      required:
        - product
      properties:
        product:
          $ref: "#/definitions/Product"
  PurchaseRequest:
    in: body
    name: "PurchaseRequest"
    required: true
    schema:
      type: object
      properties:
        lineItems:
          type: array
          items:
            $ref: "#/definitions/LineItem"

definitions:
  CreateProductResponse:
    type: object
    properties:
      product:
        $ref: "#/definitions/Product"
  EditProductResponse:
    type: object
    properties:
      product:
        $ref: "#/definitions/Product"
  ListProductsResponse:
    type: object
    properties:
      products:
        type: array
        items:
          $ref: "#/definitions/Product"
  GetStatsResponse:
    type: object
    properties:
      topSales:
        type: object
        properties:
          lineItems:
            type: array
            items:
              properties:
                title:
                  type: string
                count:
                  type: integer
          topItems:
            type: array
            items:
              properties:
                title:
                  type: string
                count:
                  type: integer
          lastSales:
            type: array
            items:
              properties:
                date:
                  type: integer
                  format: int64
                totalProfit:
                  type: integer
  PurchaseResponse:
     type: object
     properties:
      transaction:
        $ref: "#/definitions/Transaction"
  
  Product:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      title:
        type: string
      description:
        type: string
      price:
        type: number
      image: 
        type: string
  LineItem:
    type: object
    properties:
      id:
        type: integer
        format: int64
      count:
        type: integer
        format: int32
        
  Transaction:
    type: object
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      lineItems:
        type: array
        items: 
            $ref: "#/definitions/LineItem"
      totalPrice:
        type: integer
        format: int32
      creationTime:
        type: integer
        format: int64
     